# Generated by Django 5.1.6 on 2025-03-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdb',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
