{
  "address": ["Personal information extractor"],
  "appointment": ["SMB-related info"],
  "brand": ["VCC-related info"],
  "certification": ["VCC-related info"],
  "city": ["Personal information extractor"],
  "commitment": ["Content-based structure information"],
  "company": ["VCC-related info"],
  "compare": ["Content-based structure information"],
  "composition": ["VCC-related info"],
  "contact": ["Personal information extractor"],
  "contractor": ["SMB-related info"],
  "cost": ["SMB-related info"],
  "decision": ["Content-based structure information"],
  "door": ["VCC-related info"],
  "email": ["Personal information extractor"],
  "engagement": ["Content-based structure information"],
  "estimate": ["SMB-related info"],
  "feature": ["VCC-related info"],
  "follow-up": ["Content-based structure information"],
  "future": ["Content-based structure information"],
  "hesitation": ["Content-based structure information"],
  "homeowner": ["Personal information extractor"],
  "house": ["Personal information extractor"],
  "inspect": ["SMB-related info"],
  "inspection": ["SMB-related info"],
  "intent": ["Content-based structure information"],
  "journey": ["Content-based structure information"],
  "location": ["Personal information extractor"],
  "manager": ["Personal information extractor"],
  "material": ["VCC-related info"],
  "name": ["Personal information extractor"],
  "next step": ["Content-based structure information"],
  "payment": ["SMB-related info"],
  "phone": ["Personal information extractor"],
  "planning": ["Content-based structure information"],
  "price": ["SMB-related info"],
  "problem": ["Content-based structure information"],
  "product": ["VCC-related info"],
  "property": ["Personal information extractor"],
  "purchase": ["Content-based structure information"],
  "question": ["Content-based structure information"],
  "repair": ["SMB-related info"],
  "research": ["Content-based structure information"],
  "resolution": ["Content-based structure information"],
  "role": ["Personal information extractor"],
  "roof": ["VCC-related info"],
  "schedule": ["SMB-related info"],
  "service": ["SMB-related info"],
  "signal": ["Content-based structure information"],
  "support": ["Content-based structure information"],
  "technician": ["SMB-related info"],
  "tenant": ["Personal information extractor"],
  "timeline": ["SMB-related info"],
  "trust": ["Content-based structure information"],
  "vcc": ["VCC-related info"],
  "warranty": ["VCC-related info"],
  "window": ["VCC-related info"],
  "zip": ["Personal information extractor"]
}
